apiVersion: apps/v1
kind: Deployment
metadata:
  name: twilio-autobots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twilio-autobots
  template:
    metadata:
      labels:
        app: twilio-autobots
    spec:
      containers:
      - name: twilio-autobots-container
        image: jesrbegl/twilio-autobots
        ports:
        - containerPort: 8080